spring:
  application:
    name: llm-service
  profiles:
    active: ${ACTIVE_PROFILE:test}
  jpa:
    open-in-view: false
  jackson:
    time-zone: Europe/Berlin
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  mail:
    host: smtp.ionos.de
    port: 465
    username: monitoring@flow-suite.de
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true

server:
  servlet:
    context-path: /api/v1

client:
  name: ${CLIENT_NAME}
  secret: ${CLIENT_SECRET}