spring:
  application:
    name: rag-service
  profiles:
    active: ${ACTIVE_PROFILE}
  jpa:
    open-in-view: false
  jackson:
    time-zone: Europe/Berlin
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  servlet:
    context-path: /api/v1

client:
  name: ${CLIENT_NAME}
  secret: ${CLIENT_SECRET}