logging:
  level:
    de.flowsuite: DEBUG
    org.springframework.security: TRACE

server:
  port: 8083

mailflow:
  api:
    base-url: http://localhost:8080/api/v1
  mailbox-service:
    base-url: http://localhost:8081/api/v1
  llm-service:
    base-url: http://localhost:8082/api/v1
  rag-service:
    base-url: http://localhost:8083/api/v1

langchain:
  debug: true