spring:
  application:
    name: rag-service
  profiles:
    active: ${ACTIVE_PROFILE:test}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
  jackson:
    time-zone: Europe/Berlin

server:
  servlet:
    context-path: /api/v1
  port: ${PORT:8080}

client:
  name: ${CLIENT_NAME}
  secret: ${CLIENT_SECRET}

mail:
  host: smtp.ionos.de
  port: 465
  username: monitoring@flow-suite.de
  password: ${MAIL_PASSWORD}