spring:
  application:
    name: rag-service
  profiles:
    active: ${ACTIVE_PROFILE}
  jpa:
    open-in-view: false
  jackson:
    time-zone: Europe/Berlin

server:
  servlet:
    context-path: /api/v1