spring:
  application:
    name: mailbox-service
  profiles:
    active: ${ACTIVE_PROFILE:test}
  jpa:
    open-in-view: false
  jackson:
    time-zone: Europe/Berlin
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  servlet:
    context-path: /api/v1
  port: ${PORT:8080}

client:
  name: ${CLIENT_NAME}
  secret: ${CLIENT_SECRET}

mail:
  host: smtp.ionos.de
  port: 465
  username: monitoring@flow-suite.de
  password: ${MAIL_PASSWORD}