name: Build and Push to AWS ECR

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ECR_REPOSITORY_URI: ${{ secrets.AWS_ECR_REPOSITORY_URI }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push rag-service
        uses: docker/build-push-action@v6
        with:
          context: ./rag-service
          push: true
          tags: ${{ env.AWS_ECR_REPOSITORY_URI }}-rag-service:latest

      - name: Build & Push llm-service
        uses: docker/build-push-action@v6
        with:
          context: ./llm-service
          push: true
          tags: ${{ env.AWS_ECR_REPOSITORY_URI }}-llm-service:latest

      - name: Build & Push mailbox-service
        uses: docker/build-push-action@v6
        with:
          context: ./mailbox-service
          push: true
          tags: ${{ env.AWS_ECR_REPOSITORY_URI }}-mailbox-service:latest